### ISSUE TITLE
Having accounts.firefox.com as a "top site" will disconnect Sync as a thumbnail is generated. [bz1395485]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#369] opened 2017-09-01 00:31 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1395485

from the WTF department...

STR:
* Have accounts.firefox.com as a "top site" such that it appears on about:newtab etc.
* Refresh the profile.
* After a few seconds the new profile is kicked out of Sync.

What happens is that the page thumbnailer loads accounts.firefox.com to create a thumbnail. The webchannel mechanism kicks in and we see a fxaccounts:fxa_status message followed by a fxaccounts:logout message, and we kick the user out of sync.

For context, the "refresh profile" command blindly copies signedInUser.json to the new profile.

In my test-case, the we respond to the fxa_status message with:
{"signedInUser":
  {"email":"xxxx@gmail.com",
  "sessionToken":"big_hex_value",
  "uid", "big_hex_value",
  "verified":true}
  },
  "capabilities":{"engines":["addresses"]}
}

and we immediate get:
{"command":"fxaccounts:logout","data":{"uid":"big_hex_value"},"messageId":null}

(where the UID matches in both cases, hence we process the logout.)

Shane, any clues why we kick the user out in that case?

**Comment by shane-tomlinson** [comment] 2017-09-04 14:09
I believe this has the same root cause as https://github.com/mozilla/fxa-content-server/issues/5345

**Comment by rfk** [comment] 2017-09-13 23:29
Should we just close this as a dup of the above #5354?  IIUC the proposed fix would be to fix that as the underlying bug, delaying the "logout" message that's generated in the event of an incorrect uid.

**Comment by vbudhram** [comment] 2017-12-15 16:55
from mtg: closed in bugzilla

**Closed by vbudhram** 2017-12-15 16:55 UTC
Labels: waffle:backlog, ❤
