### ISSUE TITLE
Email opt-ins are not captured if user verifies in a second browser [bz1281930]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#167] opened 2016-07-18 03:45 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1281930

Created attachment 8764724
German language pref center

In testing the new CRM migration, we discovered that if a user creates a Firefox account on non-en languages and ticks the box to opt-into email, the opt-in preference is not captured and not passed through to basket. 

I've confirmed this error in German, French and Pt-br. I have attached a screenshot of the accounts preferences in German. This account was created and the opt-in box was checked. Notice that the "Subscribe" option is available and the email address has not been recorded as an opt-in. The expected behavior should be that "Abonnieren" (subscribe) should be the German equivalent of "Unsubscribe."

**Comment by shane-tomlinson** [comment] 2016-07-18 16:49
I thought we didn't show the button for locales we do not accept.

**Comment by shane-tomlinson** [comment] 2016-07-25 11:26
The problem is not limited to en accounts. The problem is when users verify in a 2nd browser. Updating the title.

**Comment by davismtl** [comment] 2016-11-30 21:38
@shane-tomlinson @rfk  
Given that marketing is pushing very hard to drive newsletter signups, do we have an estimate on how much work would be required to fix this? This could really help them out.

@chrismore filed a feature request to get our help to get more newsletter sign-ups but it seems we should fix what is broken first. /fxa-features/issues/55

**Comment by rfk** [comment] 2016-11-30 22:07
Perhaps we should bite the bullet and refactor the way we handle these subscriptions, to move the work into the backend rather than doing it all on the front-end.  This would both fix the verify-in-a-different-browser issue, and make it easier to manage on login.

I estimate close to 1 person-sprint's worth of work to do such a refactor.

**Comment by shane-tomlinson** [comment] 2016-12-01 09:43
> I estimate close to 1 person-sprint's worth of work to do such a refactor.

👍 - I'd estimate the same.

**Comment by rfk** [comment] 2016-12-01 19:24
@davismtl, I'll defer to your PM's judgement based on those estimates, as to when and how to move forward from here

**Comment by davismtl** [comment] 2017-05-08 16:59
@ryanfeeley or @shane-tomlinson 
Do you know what % of users confirm their email during registration from a different device? I can't seem to find that number.

**Comment by ryanfeeley** [comment] 2017-05-08 18:36
@davismtl I'll check datadog but off the top of my head I thought it was around 1/2

**Comment by rfk** [comment] 2017-05-11 02:47
This came up again in conversations recently, so I wanted to sketch what a hypothetical refactor this this might look like, to help inform whether we can take it on.  Said hypothetical new world might look like this:

* Remove all the behind-the-scenes code for doing the opt-in from the front-end verification page.
* Add a new field to the `/v1/account/create` payload called `"marketingOptIn"`, and have the content-server pass a boolean `true` or `false` depending on whether the user checked the checkbox.
* Have the auth-server do the following when it receives said field:
    * when the account gets created, stash the value of "marketingOptIn" in memcache or somewhere
    * when the account later gets verified, read the stashed value of "marketingOptIn" and include it in the SQS message that we publish out to attached services
* Have the fxa-basket-proxy do the following:
    * when it receives a verified event via SQS, look for the "marketingOptIn" property and perform the opt-in if it's set to `true`

@shane-tomlinson does this sound plausible?  Am I missing anything obvious?

> I estimate close to 1 person-sprint's worth of work to do such a refactor.

After thinking through the above, this estimate doesn't feel wildly off.  It would need to be someone's primary focus for a train cycle in order to push through all the missing pieces.

**Comment by shane-tomlinson** [comment] 2017-05-11 09:45
@rfk - this seems reasonable. I'm trying to think if there are possible simplifications and can't off the top of my head. 

One thing we could consider, to reduce the number of entities that find out whether the user has opted into Basket, is to have the auth server do some back channel chat with the basket proxy that says "user with uid X wishes to opt into Marketing". The basket proxy could store the data in memcached or redis itself. When the auth server subsequently sends the SQS message, we wouldn't need to broadcast `marketingOptIn` to the world since Basket would already know this.

**Comment by vladikoff** [comment] 2017-07-05 15:51
cc @seanmonstar

**Comment by seanmonstar** [comment] 2017-07-05 15:56
I couldn't find this bug during the all hands, so I filed https://github.com/mozilla/fxa-content-server/issues/5195

**Comment by seanmonstar** [comment] 2017-07-18 22:06
All the various pieces of this are merged!

**Closed by seanmonstar** 2017-07-18 22:06 UTC
Labels: P1, waffle:active
