### ISSUE TITLE
Features are displayed on "Get the most out of your account" page [bz1554710]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#662] opened 2019-05-28 00:44 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1554710

Created attachment 9067792
Captura de pantalla (94).png

**Note**
* Prerequisites:
To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:
* identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
* browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
* Restart the browser.

**Affected versions**
* Tested on Nightly 69.0a1 (2019-05-27)

**Affected platforms**
* Tested on Windows 10

**Steps to reproduce**
1. Go to about:welcome page
2. Enter valid email account.
3. Click "Continue".
4. Click on "Create account"

**Expected result**
* Features are not displayed on "Get the most out of your account" page

**Actual result**
* Features are displayed on "Get the most out of your account" page

**Comment by shane-tomlinson** [comment] 2019-05-28 10:50
Closed as by design from https://mozilla.invisionapp.com/share/3GRZJ9J65A9#/screens/362776356

**Closed by shane-tomlinson** 2019-05-28 10:50 UTC
