### ISSUE TITLE
Unexpected error after verification email Error [bz1395348]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#368] opened 2017-08-31 00:31 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1395348

After an attempt to sign in by email verification, there was an error. 
Then adding a secondary email changed that error to an Unexpected error. 

However in both cases, the email was not received when attempting to login again. 

- My email provider is FastMail.com, hosted on my own domain lindeijer.nl
- Uses the FastMail web interface as well as using the standard Android Email app through IMAP
-Issue arose on Firefox on my Xubuntu laptop (desktop)
-First error was that the email was returned, new error is "Unexpected error". Using the Network tab in the Inspector, I noticed that the request to https://api.accounts.firefox.com/v1/account/login?keys=true upon login is returning with "500 Internal Server Error", errno 999.

**Comment by rfk** [comment] 2017-09-13 23:24
This was caused by https://github.com/mozilla/fxa-auth-server/pull/2098 which has now been merged, and the user is unblocked

**Closed by rfk** 2017-09-13 23:24 UTC
Labels: waffle:next
